citizen_key_web:
    resource: "@WebBundle/Controller/"
    type:     annotation
    prefix:   /app

citizen_key_core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /
