# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    web.form_authenticator:
        class: CitizenKey\WebBundle\Security\FormAuthenticator
        arguments: ["@doctrine.orm.entity_manager", "@router"]
    web.generic_voter:
        class: CitizenKey\WebBundle\Security\GenericVoter
        arguments: ["@doctrine.orm.entity_manager", "@session", "@security.access.decision_manager"]
        tags:
            - { name: security.voter }
        public: false
