<?php

namespace CitizenKey\CoreBundle\Repository;

/**
 * AdminLevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminLevelRepository extends \Doctrine\ORM\EntityRepository
{
}
