<?php

namespace CitizenKey\CoreBundle\Repository;

/**
 * EmailAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
