<?php

namespace CitizenKey\CoreBundle\Repository;

/**
 * StreetNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreetNumberRepository extends \Doctrine\ORM\EntityRepository
{
}
