<?php

namespace CitizenKey\CoreBundle\Repository;

/**
 * StreetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreetRepository extends \Doctrine\ORM\EntityRepository
{
}
