<?php

namespace CitizenKey\CoreBundle\Repository;

/**
 * ZipCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZipCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
